In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/heart-failure-prediction/heart.csv


In [2]:
from sklearn.model_selection import train_test_split
import warnings
warnings.filterwarnings("ignore")

In [3]:
df = pd.read_csv("/kaggle/input/heart-failure-prediction/heart.csv")

In [4]:
df.head(5)

Age Sex ChestPainType  RestingBP  Cholesterol  FastingBS RestingECG  MaxHR  \
0   40   M           ATA        140          289          0     Normal    172   
1   49   F           NAP        160          180          0     Normal    156   
2   37   M           ATA        130          283          0         ST     98   
3   48   F           ASY        138          214          0     Normal    108   
4   54   M           NAP        150          195          0     Normal    122   

  ExerciseAngina  Oldpeak ST_Slope  HeartDisease  
0              N      0.0       Up             0  
1              N      1.0     Flat             1  
2              N      0.0       Up             0  
3              Y      1.5     Flat             1  
4              N      0.0       Up             0

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 918 entries, 0 to 917
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Age             918 non-null    int64  
 1   Sex             918 non-null    object 
 2   ChestPainType   918 non-null    object 
 3   RestingBP       918 non-null    int64  
 4   Cholesterol     918 non-null    int64  
 5   FastingBS       918 non-null    int64  
 6   RestingECG      918 non-null    object 
 7   MaxHR           918 non-null    int64  
 8   ExerciseAngina  918 non-null    object 
 9   Oldpeak         918 non-null    float64
 10  ST_Slope        918 non-null    object 
 11  HeartDisease    918 non-null    int64  
dtypes: float64(1), int64(6), object(5)
memory usage: 86.2+ KB


In [6]:
df.isnull().sum()

Age               0
Sex               0
ChestPainType     0
RestingBP         0
Cholesterol       0
FastingBS         0
RestingECG        0
MaxHR             0
ExerciseAngina    0
Oldpeak           0
ST_Slope          0
HeartDisease      0
dtype: int64

In [7]:
print(df["ChestPainType"].unique())
print(df["RestingECG"].unique())
print(df["ST_Slope"].unique())

['ATA' 'NAP' 'ASY' 'TA']
['Normal' 'ST' 'LVH']
['Up' 'Flat' 'Down']


In [8]:
one_hot = pd.get_dummies(df, columns = ['Sex', 'ChestPainType', 'RestingECG', 'ExerciseAngina', 'ST_Slope'], dtype = 'float')

In [9]:
one_hot.head(5)

Age  RestingBP  Cholesterol  FastingBS  MaxHR  Oldpeak  HeartDisease  \
0   40        140          289          0    172      0.0             0   
1   49        160          180          0    156      1.0             1   
2   37        130          283          0     98      0.0             0   
3   48        138          214          0    108      1.5             1   
4   54        150          195          0    122      0.0             0   

   Sex_F  Sex_M  ChestPainType_ASY  ...  ChestPainType_NAP  ChestPainType_TA  \
0    0.0    1.0                0.0  ...                0.0               0.0   
1    1.0    0.0                0.0  ...                1.0               0.0   
2    0.0    1.0                0.0  ...                0.0               0.0   
3    1.0    0.0                1.0  ...                0.0               0.0   
4    0.0    1.0                0.0  ...                1.0               0.0   

   RestingECG_LVH  RestingECG_Normal  RestingECG_ST  ExerciseAngina_N  \
0             0.0                1.0            0.0               1.0   
1             0.0                1.0            0.0               1.0   
2             0.0                0.0            1.0               1.0   
3             0.0                1.0            0.0               0.0   
4             0.0                1.0            0.0               1.0   

   ExerciseAngina_Y  ST_Slope_Down  ST_Slope_Flat  ST_Slope_Up  
0               0.0            0.0            0.0          1.0  
1               0.0            0.0            1.0          0.0  
2               0.0            0.0            0.0          1.0  
3               1.0            0.0            1.0          0.0  
4               0.0            0.0            0.0          1.0  

[5 rows x 21 columns]

In [10]:
one_hot.shape

(918, 21)

In [11]:
train = one_hot.drop(columns = ['HeartDisease'])
target = one_hot['HeartDisease']

In [12]:
x_train, x_test, y_train, y_test = train_test_split(train, target, test_size = 0.2, random_state = 40)

In [13]:
from sklearn.preprocessing import StandardScaler

In [14]:
cols = ['Age', 'RestingBP', 'Cholesterol', 'MaxHR']
scaler = StandardScaler()
x_train[cols] = scaler.fit_transform(x_train[cols])
x_test[cols] = scaler.transform(x_test[cols])

# Support Vector Classifier

In [15]:
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC

In [16]:
param_grid = {
    'C': [0.1, 1, 10, 100],
    'kernel': ['linear', 'poly', 'rbf', 'sigmoid'],
    'gamma': [0.001, 0.01, 0.1, 1]
}

In [17]:
svc = SVC()
grid_search = GridSearchCV(estimator=svc, param_grid=param_grid, cv=5, scoring='accuracy')

In [18]:
grid_search.fit(x_train, y_train)

print("Best parameters for SVC:", grid_search.best_params_)
print("Best cross-validation score:", grid_search.best_score_)

Best parameters for SVC: {'C': 1, 'gamma': 0.1, 'kernel': 'rbf'}
Best cross-validation score: 0.8733482434069518


In [19]:
best_svc_model = grid_search.best_estimator_

# Logistic Regression

In [20]:
from sklearn.linear_model import LogisticRegression

In [21]:
logreg = LogisticRegression(max_iter=1000)
param_grid = {
    'C': [0.01, 0.1, 1, 10, 100],
    'solver': ['newton-cg', 'lbfgs', 'liblinear', 'sag', 'saga'],
    'penalty': ['l2', 'none', 'l1']
}

grid_search = GridSearchCV(estimator=logreg, param_grid=param_grid, cv=5, scoring='accuracy')

grid_search.fit(x_train, y_train)

print("Best parameters for Logistic Regression:", grid_search.best_params_)
print("Best cross-validation score:", grid_search.best_score_)

Best parameters for Logistic Regression: {'C': 1, 'penalty': 'l2', 'solver': 'liblinear'}
Best cross-validation score: 0.8583356630323362


In [22]:
best_lr_model = grid_search.best_estimator_

# Gaussian Naive Bayes

In [23]:
from sklearn.naive_bayes import GaussianNB

gnb = GaussianNB()

param_grid = {
    'var_smoothing': [1e-5, 1e-4, 1e-3, 1e-2, 1e-1, 1]
}

grid_search = GridSearchCV(estimator=gnb, param_grid=param_grid, cv=5, scoring='accuracy')

grid_search.fit(x_train, y_train)

print("Best parameters for Naive Bayes:", grid_search.best_params_)
print("Best cross-validation score:", grid_search.best_score_)

Best parameters for Naive Bayes: {'var_smoothing': 0.1}
Best cross-validation score: 0.8569844376106607


In [24]:
best_gnb_model = grid_search.best_estimator_

# Tesing the models

In [25]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

SVC MODEL

In [26]:
y_pred = best_svc_model.predict(x_test)

accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

print("Classification Report:")
print(classification_report(y_test, y_pred))

print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Accuracy: 0.8858695652173914
Classification Report:
              precision    recall  f1-score   support

           0       0.90      0.81      0.85        75
           1       0.88      0.94      0.91       109

    accuracy                           0.89       184
   macro avg       0.89      0.87      0.88       184
weighted avg       0.89      0.89      0.88       184

Confusion Matrix:
[[ 61  14]
 [  7 102]]


Logistic Regression Model

In [27]:
y_pred = best_lr_model.predict(x_test)

accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

print("Classification Report:")
print(classification_report(y_test, y_pred))

print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Accuracy: 0.8913043478260869
Classification Report:
              precision    recall  f1-score   support

           0       0.88      0.85      0.86        75
           1       0.90      0.92      0.91       109

    accuracy                           0.89       184
   macro avg       0.89      0.89      0.89       184
weighted avg       0.89      0.89      0.89       184

Confusion Matrix:
[[ 64  11]
 [  9 100]]


In [28]:
y_pred = best_gnb_model.predict(x_test)

accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

print("Classification Report:")
print(classification_report(y_test, y_pred))

print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Accuracy: 0.8913043478260869
Classification Report:
              precision    recall  f1-score   support

           0       0.87      0.87      0.87        75
           1       0.91      0.91      0.91       109

    accuracy                           0.89       184
   macro avg       0.89      0.89      0.89       184
weighted avg       0.89      0.89      0.89       184

Confusion Matrix:
[[65 10]
 [10 99]]


In [29]:
import pickle

In [30]:
filename = '/kaggle/working/' + 'finalized_model.sav'
pickle.dump(best_gnb_model, open(filename, 'wb'))